### ISSUE TITLE
New LRM v4.3.1 don't work 

### ISSUE THREAD

**Issue by JLD95** [lrmapp/issues#17] opened 2021-10-01 15:38 UTC
Hi,

I uninstalled my old LRM v4. After sucessfull install new LRM v4.3.1, the lanch LRM don't open any windows, seems don't work.
I use Win10 with user account like for old LRM.

It is possible to have a link to the previous version ?

**Comment by allebb** [comment] 2021-10-01 15:56
Hi JLD95,

Could you check if it's running in the system tray maybe?

Also, might be worth you checking inside the Microsoft Event Viewer too -
there may be some errors that have been captured there.

This seems to be a one-off issue affecting you given that there have been
over 200 downloads of the new client today alone and this is the first time
I've heard of this specific issue :(

Let me know if there are any issues reported in the Event Viewer and I'll
do my best to advise on next steps etc :+1

Cheers,
Bobby

**Comment by kikored1** [comment] 2021-10-01 18:51
> 
> 
> Hi,
> 
> I uninstalled my old LRM v4. After sucessfull install new LRM v4.3.1, the lanch LRM don't open any windows, seems don't work. I use Win10 with user account like for old LRM.
> 
> It is possible to have a link to the previous version ?

Hi,

I have the same Issue. 
The program opens and stops immediately after.
I was able to use the old version of LRM the same morning.

My FSUIPC version is up to date.

**Comment by AFR2638** [comment] 2021-10-02 06:46
Hi, 
I've as well installed the last LRM version, but do not works.
FSUIPC and microsoft framework are uptodate.
it can be seen dung when doubble click onj LRM icon that something appens, but nothing more is displayed.
Nothing visible in the system tray.

Thanks you for support
JM

**Comment by allebb** [comment] 2021-10-02 07:16
Hi guys, 

Whilst we continue to investigate why this is occurring for a handful of users, I've posted an update on our forums as to what we recommend to those users that are affected by this issue and how they can get back and up running as quickly as possible:
https://forums.fshub.io/t/having-issues-running-the-latest-lrm-client-4-3-1/58

The problem that we have at the moment is that we are unable to replicate the issue on our own systems and also have very little error log information that is being sent to us from the affected users which would ultimately help us identify why this is occurring - therefore if you have any errors in the Event Viewer please post here so we have more information and will help us in diagnosing and fixing this issue.

Thanks,
Bobby

**Comment by JLD95** [comment] 2021-10-04 15:21
Nom du journal :Application
Source :       .NET Runtime
Date :         04/10/2021 17:18:44
ID de l’événement :1026
Catégorie de la tâche :Aucun
Niveau :       Erreur
Mots clés :    Classique
Utilisateur :  N/A
Ordinateur :   JLD-PC5
Description :
Application : LRM.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.FormatException
   à System.Number.StringToNumber(System.String, System.Globalization.NumberStyles, NumberBuffer ByRef, System.Globalization.NumberFormatInfo, Boolean)
   à System.Number.ParseDecimal(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
   à System.Convert.ToDecimal(System.String)
   à LRM.Blackbox.RadioFreqency..ctor(System.String)
   à LRM.Blackbox.FDRData..ctor()
   à LRM.Blackbox.DataRecorder..ctor()
   à LRM.MainForm..ctor(System.String[])
   à LRM.Program.Main(System.String[])


XML de l’événement :
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-10-04T15:18:44.8948569Z" />
    <EventRecordID>49180</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>JLD-PC5</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application : LRM.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.FormatException
   à System.Number.StringToNumber(System.String, System.Globalization.NumberStyles, NumberBuffer ByRef, System.Globalization.NumberFormatInfo, Boolean)
   à System.Number.ParseDecimal(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
   à System.Convert.ToDecimal(System.String)
   à LRM.Blackbox.RadioFreqency..ctor(System.String)
   à LRM.Blackbox.FDRData..ctor()
   à LRM.Blackbox.DataRecorder..ctor()
   à LRM.MainForm..ctor(System.String[])
   à LRM.Program.Main(System.String[])

</Data>
  </EventData>
</Event>

**Comment by JLD95** [comment] 2021-10-04 15:22
Nom du journal :Application
Source :       Application Error
Date :         04/10/2021 17:18:45
ID de l’événement :1000
Catégorie de la tâche :(100)
Niveau :       Erreur
Mots clés :    Classique
Utilisateur :  N/A
Ordinateur :   JLD-PC5
Description :
Nom de l’application défaillante LRM.exe, version : 4.3.1.0, horodatage : 0x6152cef1
Nom du module défaillant : KERNELBASE.dll, version : 10.0.19041.1266, horodatage : 0x6e3598ea
Code d’exception : 0xe0434352
Décalage d’erreur : 0x0012b5b2
ID du processus défaillant : 0x434c
Heure de début de l’application défaillante : 0x01d7b9331f2457a4
Chemin d’accès de l’application défaillante : C:\Program Files (x86)\Landing Rate Monitor\LRM.exe
Chemin d’accès du module défaillant: C:\WINDOWS\System32\KERNELBASE.dll
ID de rapport : fe4118fa-3579-40e2-8ab0-5e6cb9e183f1
Nom complet du package défaillant : 
ID de l’application relative au package défaillant : 
XML de l’événement :
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-10-04T15:18:45.2161484Z" />
    <EventRecordID>49181</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>JLD-PC5</Computer>
    <Security />
  </System>
  <EventData>
    <Data>LRM.exe</Data>
    <Data>4.3.1.0</Data>
    <Data>6152cef1</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.1266</Data>
    <Data>6e3598ea</Data>
    <Data>e0434352</Data>
    <Data>0012b5b2</Data>
    <Data>434c</Data>
    <Data>01d7b9331f2457a4</Data>
    <Data>C:\Program Files (x86)\Landing Rate Monitor\LRM.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>fe4118fa-3579-40e2-8ab0-5e6cb9e183f1</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by JLD95** [comment] 2021-10-04 15:23
Nom du journal :Application
Source :       .NET Runtime
Date :         04/10/2021 17:18:53
ID de l’événement :1026
Catégorie de la tâche :Aucun
Niveau :       Erreur
Mots clés :    Classique
Utilisateur :  N/A
Ordinateur :   JLD-PC5
Description :
Application : LRM.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.FormatException
   à System.Number.StringToNumber(System.String, System.Globalization.NumberStyles, NumberBuffer ByRef, System.Globalization.NumberFormatInfo, Boolean)
   à System.Number.ParseDecimal(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
   à System.Convert.ToDecimal(System.String)
   à LRM.Blackbox.RadioFreqency..ctor(System.String)
   à LRM.Blackbox.FDRData..ctor()
   à LRM.Blackbox.DataRecorder..ctor()
   à LRM.MainForm..ctor(System.String[])
   à LRM.Program.Main(System.String[])


XML de l’événement :
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-10-04T15:18:53.6438298Z" />
    <EventRecordID>49184</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>JLD-PC5</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application : LRM.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.FormatException
   à System.Number.StringToNumber(System.String, System.Globalization.NumberStyles, NumberBuffer ByRef, System.Globalization.NumberFormatInfo, Boolean)
   à System.Number.ParseDecimal(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
   à System.Convert.ToDecimal(System.String)
   à LRM.Blackbox.RadioFreqency..ctor(System.String)
   à LRM.Blackbox.FDRData..ctor()
   à LRM.Blackbox.DataRecorder..ctor()
   à LRM.MainForm..ctor(System.String[])
   à LRM.Program.Main(System.String[])

</Data>
  </EventData>
</Event>

**Comment by JLD95** [comment] 2021-10-04 15:23
Nom du journal :Application
Source :       Application Error
Date :         04/10/2021 17:18:53
ID de l’événement :1000
Catégorie de la tâche :(100)
Niveau :       Erreur
Mots clés :    Classique
Utilisateur :  N/A
Ordinateur :   JLD-PC5
Description :
Nom de l’application défaillante LRM.exe, version : 4.3.1.0, horodatage : 0x6152cef1
Nom du module défaillant : KERNELBASE.dll, version : 10.0.19041.1266, horodatage : 0x6e3598ea
Code d’exception : 0xe0434352
Décalage d’erreur : 0x0012b5b2
ID du processus défaillant : 0x3bc4
Heure de début de l’application défaillante : 0x01d7b93324656bf0
Chemin d’accès de l’application défaillante : C:\Program Files (x86)\Landing Rate Monitor\LRM.exe
Chemin d’accès du module défaillant: C:\WINDOWS\System32\KERNELBASE.dll
ID de rapport : a41e39c3-e723-4d47-8997-2935fc49a0eb
Nom complet du package défaillant : 
ID de l’application relative au package défaillant : 
XML de l’événement :
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-10-04T15:18:53.9180795Z" />
    <EventRecordID>49185</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>JLD-PC5</Computer>
    <Security />
  </System>
  <EventData>
    <Data>LRM.exe</Data>
    <Data>4.3.1.0</Data>
    <Data>6152cef1</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.1266</Data>
    <Data>6e3598ea</Data>
    <Data>e0434352</Data>
    <Data>0012b5b2</Data>
    <Data>3bc4</Data>
    <Data>01d7b93324656bf0</Data>
    <Data>C:\Program Files (x86)\Landing Rate Monitor\LRM.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>a41e39c3-e723-4d47-8997-2935fc49a0eb</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by JLD95** [comment] 2021-10-04 15:25
Two errors in event viewer for each LRM run
Erreur	04/10/2021 17:23:27	Application Error	1000	(100)
Erreur	04/10/2021 17:23:26	.NET Runtime	1026	Aucun

details in previous posts

**Comment by allebb** [comment] 2021-10-04 15:28
HI JLD,

I *think* I know what the problem is now... I think it is because the
french language you are using for Windows is incorrectly formatting decimal
numbers (I think french language uses "," instead of ".")

Would you mind quickly changing Windows to use the English language and
then try opening LRM Client (just as a test for me ??)

Cheers,
Bobby

**Comment by JLD95** [comment] 2021-10-04 15:35
Same errors with ENG setting

![2021-10-04](https://user-images.githubusercontent.com/5894146/135880640-68287f91-38d8-4f9e-aff8-f91c946c6894.jpg)

**Comment by allebb** [comment] 2021-10-04 15:38
Can you try changing your number format in Windows to use "." as the
decimal separator? - Maybe changing the language alone is not enough.

Here are instructions as to how to change this:
https://answers.microsoft.com/en-us/msoffice/forum/all/changing-decimal-separator-from-comma-to-dot/953556fb-00d0-45ad-bd4f-6ca8afa5025a

**Comment by JLD95** [comment] 2021-10-04 15:43
Yes it's works even with FRA windows setting; Only decimal separator setting is needed

![Presse-papiers-1](https://user-images.githubusercontent.com/5894146/135881914-390f62d3-0c9f-4266-844c-d86e31ee77dd.jpg)

**Comment by allebb** [comment] 2021-10-04 15:48
That's interesting - thanks for testing!!

I will do my best to fix the application and post an update in a day or so
:)

**Comment by KevinAviationHD** [comment] 2021-10-04 19:28
I have the same problem, I'm simply not able to open the application, when I try to open it as an administrator or normal nothing happens. The old versions work. My windows event viewer shows kernelbase.dll errors.

**Comment by allebb** [comment] 2021-10-04 19:30
Can you confirm, from the above replies if changing the "decimal point" in
Windows fixes this for you too though?

**Comment by KevinAviationHD** [comment] 2021-10-05 09:30
Unfortunetly not, the software simply doesn't open.

**Comment by allebb** [comment] 2021-10-05 09:34
Would you be able to see if there are any errors in the Microsoft Event
Viewer for LRM Client and report them here? - If so I may be able to work
out why this issue is happening on your computer?

Thanks,
Bobby

**Comment by JLD95** [comment] 2021-10-09 05:46
Hi, any news for a v4.3.2 ?

**Comment by allebb** [comment] 2021-10-17 14:59
Hi guys,

A new version of the LRM client has now been released (and, from my initial testing) seems to fix the problem, please see the blog post and the download link for LRM 4.3.2 here:

https://forums.fshub.io/t/lrm-client-4-3-2-ready-for-testing-fixes-for-client-not-starting/60

If you could report back here if this now resolves your specific issue that would be great 👍 

Sorry it's taken a while, I've been super busy the last few weeks!

**Comment by JLD95** [comment] 2021-10-17 15:15
Hi, works fine for me.

**Comment by allebb** [comment] 2022-03-01 23:46
Closing this issue as it was fixed and confirmed working by the user a while ago now and simply dropped off my radar.

**Closed as completed by allebb** 2022-03-01 23:46 UTC
Labels: awaiting user feedback
