### ISSUE TITLE
LRM won't start

### ISSUE THREAD

**Issue by diogoj95** [lrmapp/issues#1] opened 2016-04-09 18:49 UTC
I've been trying to use LRM, but it won't start. The process starts and quits almost immediately.
From Event Viewer:
http://imgur.com/a/FoziO

I've re-installed the latest version of .NET Framework but that doesn't seem to make a difference.

**Comment by allebb** [comment] 2016-04-09 19:11
Hey!

It looks as if you may be running an old version of LRM (from the screenshot you posted), please download and install version 2.3 from here: http://bobbyallen.me/landing-rate-monitor/ and see if that works in the first instance?

Also may be a good idea to check that you specially installed the x86 version (32bit) of the .NET 4.6 Runtime this is due to the fact that FSUIPC.net is 32bit only, LRM is therefore compiled as 32bit application. Sometime people assume that the x64 .NET runtime works regardless but this is not always the case.

 I'll probably combine and automate the installation of the .NET runtime in the next release :)

Hope this helps and do let me know if this doesn't help and I'll try and replicate the issue - Please let me know the version of Windows that you are running in that case too!

**Comment by allebb** [comment] 2016-04-09 19:21
Looking further at the stack trace, it appears that the client is trying to check for updates - Do you have the internet disabled on the machine that you are using? If not then it may be your firewall that is stopping the application from checking for software updates.

I guess this technically is a bug given that the application should silently fail if it cannot connect where as at the moment, it is obviously erroring given that it cannot check the remote (latest) version number against it's local version (as it never receives one).

Could you confirm if that is the case for me? - I'll get to work on handling failed network connections in the next release.

If you have blocked it on your firewall or the PC is not connected to the internet, maybe you could connect it/enable it temporarily and then disable auto-updates by de-selected the setting option like so:

![Disable automatic update checks](http://blog.bobbyallen.me/wp-content/uploads/2016/04/Disable_Update_Checks.png)

Then re-enable the firewall rule for the application/disconnect your machine from the internet again and then the tool should start no problem (as in future it will not attempt to check for updates)

**Comment by diogoj95** [comment] 2016-04-10 10:29
Hi there,

First of all, thank you for such a quick reply. I was actually surprised.

Now, I know I have the latest version of LRM (and maybe that's where the problem lies, but we'll come to that later)
![image](https://cloud.githubusercontent.com/assets/13123976/14409524/7af00dfc-ff0d-11e5-8f09-5a687300a136.png)

About the .NET Framework, I _believe_ I have the 64-bit 4.6.1 version installed. However, FSUIPC works just fine with.
I've tried to find a 32-bit-only installer on the Internet, but I wasn't able to find it. I think MS now only ships out both versions combined. And even if I did find it, it probably wouldn't let me complete the installation.
This is what happened when I tried to re-install 4.6/4.6.1:
![image](https://cloud.githubusercontent.com/assets/13123976/14409547/36529894-ff0e-11e5-9cd1-05333bb5ac73.png)

I'm using Windows 10 Pro btw.

I also disabled the Windows Firewall. Unlucky. But I would say that that's not where the problem lies because every time a new program tries to connect to the Internet, Windows shows me a popup asking if I'd like to _let it_ connect to the Internet.

Lastly, I'm not able to turn off the update check because the program's window never appears.
Like I said, the process shows up in Task Manager for like 2 seconds and then just quits.

If you can't find a cause for this problem, maybe you could provide the installer from an earlier version and see if that works? Because I've used LRM on Windows 10 on this very same computer and it worked fine.

Thanks in advance.

**Comment by diogoj95** [comment] 2016-04-10 12:50
I notices that the LRM.exe's version is 2.0.0.0, but I've actually installed it from what I believe to be the latest installer:
![image](https://cloud.githubusercontent.com/assets/13123976/14410274/3d0996be-ff23-11e5-837a-106d92e1eef2.png)

Maybe you forgot to edit the version field before compiling?

**Comment by allebb** [comment] 2016-04-11 16:55
Hey @diogoj95  - Sorry for the late reply this time.

With regards to the application version number, yeah, that's my bad, I've updated the installer version but not the main application version - I'll get that fixed in the next release too!

I see that the .NET 4.6 (Offline Installer) seems to support both x86 and x64 so yeah, assuming when you use this installer it also shows the same "already installed" message then I guess you're all good! - https://www.microsoft.com/en-us/download/details.aspx?id=48137

A link to the previous version installer (v2.2) can be found here: https://github.com/bobsta63/bobsta63.github.io/blob/master/downloads/lrm/lrm-setup-2.2.exe?raw=true - I'd really appreciate it if you could let me know how that goes after you install that - Could you let me know please?

The confusion around the 32bit runtime requirement came from here: http://forum.simflight.com/topic/80663-client-dll-64bit-version/

Hope this helps and please do let me know how you get on with v2.2 installer.

Cheers,
Bobby

**Comment by allebb** [comment] 2016-04-11 16:55
Ooops - Re-opening issue as closed by mistake.

**Comment by diogoj95** [comment] 2016-04-11 17:29
Hi,

that's fine, everyone has the right to have some rest, at least during the weekends!

LRM v2.2 is working fine for me, and I'm now able to rate my terrible landings more precisely again!!

Thanks for all the help, and if you ever need me to test future versions of LRM just let me know, I'll be glad to.

Best regards,
diogoj95

**Comment by allebb** [comment] 2016-04-14 19:36
Cheers diogoj95 - Thanks for getting back to me and confirming...

That's great to know that the previous version is working for you now - I know others are using v2.3 without any issues (including myself) so I'm stumped as to why it is different for you (i'm also on Windows 10) but I'll do some digging, fire up some vanilla Windows VM's and see if I can reproduce your issue with 2.3 as I really want to know myself and get it fixed for future users.

I'll certainly give you a shout for testing future release!

**Closed as completed by allebb** 2016-04-14 19:36 UTC

**Comment by allebb** [comment] 2016-08-10 21:54
Just to let you know that v2.4 has been released which fixes this issue.
